package io.sirix.query.compiler.optimizer.mesh;

import io.brackit.query.compiler.AST;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;

/**
 * Search space management structure for semantically equivalent QEPs.
 *
 * <p>The Mesh (Graefe/DeWitt Exodus, Weiner Section 4.2, Figure 11) groups
 * alternative plans into {@link EquivalenceClass} instances. Virtual edges
 * avoid copying shared subtrees — alternatives reference children by
 * equivalence class ID rather than duplicating AST nodes.</p>
 *
 * <p>The Mesh stores alternatives generated by:
 * <ul>
 *   <li>Rewrite rules 1-6 producing equivalent JQGM subgraphs</li>
 *   <li>Physical operator alternatives (index scan vs sequential scan)</li>
 *   <li>Join order alternatives (from commutativity + DP enumeration)</li>
 * </ul></p>
 *
 * <p>Note: Currently scaffolding for a future milestone that will wire the Mesh
 * into the optimizer pipeline for multi-plan comparison.</p>
 */
public final class Mesh {

  private final Int2ObjectOpenHashMap<EquivalenceClass> classes;
  private final Int2ObjectOpenHashMap<int[]> childClassRefs;
  private int nextClassId;

  public Mesh(int estimatedSize) {
    this.classes = new Int2ObjectOpenHashMap<>(estimatedSize);
    this.childClassRefs = new Int2ObjectOpenHashMap<>(estimatedSize);
    this.nextClassId = 0;
  }

  /**
   * Create a new equivalence class with an initial plan.
   *
   * @param initialPlan the first plan alternative (must not be null)
   * @param cost        the cost of the initial plan (must be non-negative and finite)
   * @return the new equivalence class ID
   */
  public int createClass(AST initialPlan, double cost) {
    final int classId = nextClassId++;
    final var eqClass = new EquivalenceClass(classId);
    eqClass.addAlternative(initialPlan, cost);
    classes.put(classId, eqClass);
    return classId;
  }

  /**
   * Add an alternative plan to an existing equivalence class.
   * Called when a rewrite rule produces a new equivalent subtree.
   *
   * @param classId         the target equivalence class
   * @param alternativePlan the new plan alternative (must not be null)
   * @param cost            the estimated cost (must be non-negative and finite)
   * @throws IllegalArgumentException if classId does not exist
   */
  public void addAlternative(int classId, AST alternativePlan, double cost) {
    final var eqClass = classes.get(classId);
    if (eqClass == null) {
      throw new IllegalArgumentException("Unknown equivalence class: " + classId);
    }
    eqClass.addAlternative(alternativePlan, cost);
  }

  /**
   * Get the best (lowest-cost) plan from an equivalence class.
   *
   * @param classId the equivalence class ID
   * @return the best AST alternative, or null if class not found
   */
  public AST getBestPlan(int classId) {
    final var eqClass = classes.get(classId);
    return eqClass != null ? eqClass.getBestPlan() : null;
  }

  /**
   * Get the cost of the best plan in an equivalence class.
   *
   * @param classId the equivalence class ID
   * @return the best cost, or Double.MAX_VALUE if class not found
   */
  public double getBestCost(int classId) {
    final var eqClass = classes.get(classId);
    return eqClass != null ? eqClass.getBestCost() : Double.MAX_VALUE;
  }

  /**
   * Get an equivalence class by ID.
   *
   * @param classId the equivalence class ID
   * @return the equivalence class, or null if not found
   */
  public EquivalenceClass getClass(int classId) {
    return classes.get(classId);
  }

  /**
   * Set child equivalence class references for a parent class.
   * Enables virtual edges: instead of copying shared subtrees,
   * the plan references child classes by ID. The array is defensively
   * copied to prevent external mutation.
   *
   * @param parentClassId the parent equivalence class
   * @param childClassIds array of child class IDs
   */
  public void setChildClasses(int parentClassId, int[] childClassIds) {
    childClassRefs.put(parentClassId, childClassIds.clone());
  }

  /**
   * Get child class references for a parent class.
   *
   * @param parentClassId the parent equivalence class
   * @return array of child class IDs (defensively copied), or null if none
   */
  public int[] getChildClasses(int parentClassId) {
    final int[] refs = childClassRefs.get(parentClassId);
    return refs != null ? refs.clone() : null;
  }

  /**
   * @return the number of equivalence classes
   */
  public int classCount() {
    return classes.size();
  }

  /**
   * @return the next class ID that would be assigned
   */
  public int nextClassId() {
    return nextClassId;
  }

  /**
   * Clear all state for reuse between queries.
   */
  public void clear() {
    classes.clear();
    childClassRefs.clear();
    nextClassId = 0;
  }
}
